stages:
  - lint
  - build
  - test
  - push
  - docs
  - trigger

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

# Not making these global variables because they would get overridden in multi-project pipelines
.variables: &variables
  # The base of this repo's docker registry
  REPO_DOCKER_REGISTRY: ${CI_REGISTRY_IMAGE}
  # The image name of binaryninja-haskell-base
  BLAZE_BINARYNINJA_HASKELL_BASE_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/devops/binaryninja-haskell-base
  # Enable buildkit for more efficient layer caching
  DOCKER_BUILDKIT: "1"

# Potential build dependencies for the dind host
.script-bootstrap-dind: &script-bootstrap-dind
  - echo -e "section_start:`date +%s`:bootstrap[collapsed=true]\r\e[0KBootstrap build dependencies"
  - |
    if [ -f /etc/alpine-release ]; then
      apk add git coreutils python3
      apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/testing time
    fi
  - echo -e "section_end:`date +%s`:bootstrap\r\e[0K"

.job:
  timeout: 1h
  variables:
    <<: *variables
  before_script: &job-before-script
    - echo -e "section_start:`date +%s`:pre-env[collapsed=true]\r\e[0KEnvironment info (before_script)"
    - uname -a
    - env
    - ls -al
    - find . -maxdepth 1 \( ! -name . \) -print0 | sort -z | xargs -0 -x du -bhsc
    - echo -e "section_end:`date +%s`:pre-env\r\e[0K"

.docker-job:
  extends: .job
  image: docker:dind
  before_script:
    - *script-bootstrap-dind
    - *job-before-script
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

.setup-dockerignore: &setup-dockerignore
    - echo -e "section_start:`date +%s`:setup-dockerignore[collapsed=true]\r\e[0KSet up .dockerignore"

    # Write a .dockerignore to the build context (../). This ignores everything there except for
    # our source dependencies, since gitlab runner will have cloned our other repos to ../
    - |
      cat <<EOF >../.dockerignore
      *

      !binaryninja-haskell
      !binary-analysis

      **/.git
      **/.gitlab-ci.yml

      **/.stack
      **/.stack-work*

      **/*.cabal

      **/dist-newstyle
      **/dist
      EOF
    - |
      { echo -e '\n\n# From binary-analysis/.gitignore:';
        cat ../binary-analysis/.gitignore \
        | sed -E 's|^/|/binary-analysis/|;s|^([^/])|/binary-analysis/**/\1|';
        echo -e '\n\n# From binaryninja-haskell/.gitignore:';
        cat ../binaryninja-haskell/.gitignore \
        | sed -E 's|^/|/binaryninja-haskell/|;s|^([^/])|/binaryninja-haskell/**/\1|';
      } >>../.dockerignore

    - echo -e "section_end:`date +%s`:setup-dockerignore\r\e[0K"


.haskell-job:
  extends: .job
  image: ${REPO_DOCKER_REGISTRY}/binaryninja-haskell:pipeline-${CI_PIPELINE_IID}

lint:
  stage: lint
  extends: .job
  image: ${BLAZE_BINARYNINJA_HASKELL_BASE_IMAGE}
  needs: []
  script:
    - hlint --color=always src test demo
  allow_failure: true

build:
  stage: build
  extends: .docker-job
  needs: []
  script:
    - *setup-dockerignore
    - echo -e "section_start:`date +%s`:setup[collapsed=true]\r\e[0KProject Setup"
    - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
    - |
      for project in binary-analysis; do
        rm -rf "../${project}"
        git clone --depth=1 "${CI_REPOSITORY_URL%/*}/${project}.git" "../${project}"
      done
    - echo -e "section_end:`date +%s`:setup\r\e[0K"

    - image=${REPO_DOCKER_REGISTRY}/binaryninja-haskell
    - docker pull "${image}:latest" || true
    - docker build --pull .. -f Dockerfile
      -t "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker push "${image}:pipeline-${CI_PIPELINE_IID}"

test:
  stage: test
  extends: .haskell-job
  needs:
    - build
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cd /blaze/build/binaryninja-haskell
    - .ci/scripts/run_stack_test.py binja-header-cleaner-test binja-header-cleaner
    - .ci/scripts/run_stack_test.py binja-test binaryninja

    # Test gen-mlil-op-modules
    - make ops

push:latest:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - test
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - image=${REPO_DOCKER_REGISTRY}/binaryninja-haskell
    - docker pull "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker tag "${image}:pipeline-${CI_PIPELINE_IID}" "${image}:latest"
    - docker push "${image}:latest"

push:tag:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - test
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - image=${REPO_DOCKER_REGISTRY}/binaryninja-haskell
    - docker pull "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker tag "${image}:pipeline-${CI_PIPELINE_IID}" "${image}:tag-${CI_COMMIT_TAG}"
    - docker push "${image}:tag-${CI_COMMIT_TAG}"

pages:
  extends: .haskell-job
  stage: docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_ID == null
      when: on_success
    - if: $CI_MERGE_REQUEST_ID == null
      when: manual
  needs:
    - test
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - haddock_flags=(--no-haddock-deps)
    - pushd /blaze/build/binaryninja-haskell
    - stack haddock "${haddock_flags[@]}"
    - docs_dir=$(stack path --snapshot-doc-root "${haddock_flags[@]}")
    - popd
    # - cp -arT "$docs_dir" public
    - mkdir public
    - touch public/index.html
  allow_failure: true
  artifacts:
    paths:
      - public
    expire_in: 12 hours

trigger-blaze:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: trigger
  trigger: ${CI_PROJECT_NAMESPACE}/blaze

cleanup:
  stage: .post
  when: always
  extends: .docker-job
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache --update bash
    - images=${REPO_DOCKER_REGISTRY}/binaryninja-haskell
    - "# Untag all images created by this pipeline so we don't waste space on CI runner"
    - |
      bash -c '
        images=${REPO_DOCKER_REGISTRY}/binaryninja-haskell
        tags=()
        for image in "${images[@]}"; do
          tags+=(
            "${image}:pipeline-${CI_PIPELINE_IID}"
            "${CI_COMMIT_TAG:+${image}:tag-${CI_COMMIT_TAG}}"
            )
        done
        for i in "${!tags[@]}"; do if [ -z "${tags[$i]}" ]; then unset tags[$i]; fi; done
        echo "${tags[@]}"
        docker image rm "${tags[@]}" || true
      '
