resolver: lts-19.5
compiler: ghc-9.0.2

packages:
  - .
  - binja-header-cleaner

extra-deps:
  - ../binary-analysis
  - git: https://github.com/protolude/protolude
    commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b
